import type { Project, UserProfile, UserSession } from '../types'
import { hydrateLocalCollection, readLocalCollection, saveLocalAndRemoteCollection } from './remoteRecords'

export const PROCUREMENT_PHASES = ['New Requirement','Pricing / RFQ','Quote Preparation','Customer Approval / Funding','PO Preparation','Ordered','Shipping','Receiving','Kitting / Staging','Complete'] as const
export type ProcurementPhase = typeof PROCUREMENT_PHASES[number]
export type ProcurementHealth = 'On Track'|'Attention'|'Critical'|'On Hold'|'Complete'
export type ActionStatus = 'Open'|'In Progress'|'Complete'|'Cancelled'
export type ProcurementNote={id:string;projectId:string;text:string;createdBy:string;createdByName:string;createdAt:string;meetingDate?:string;type:'Weekly Sync'|'General'}
export type ProcurementAction={id:string;projectId:string;description:string;ownerId:string;ownerName:string;assignedBy:string;assignedByName:string;assignedAt:string;dueDate:string;status:ActionStatus;completedAt?:string;priority:'Low'|'Medium'|'High'|'Critical';comment?:string;meetingDate?:string}
export type DiscussionFlag={id:string;projectId:string;reason:string;flaggedBy:string;flaggedByName:string;flaggedAt:string;resolvedAt?:string;resolvedBy?:string}
export type ProcurementOverride={projectId:string;phase?:ProcurementPhase;phaseEnteredAt?:string;health?:ProcurementHealth;reason?:string;updatedBy:string;updatedAt:string}
export type MeetingSnapshot={id:string;meetingDate:string;createdBy:string;createdAt:string;projects:Record<string,{phase:ProcurementPhase;health:ProcurementHealth;poCount:number;poValue:number;trackingCount:number;received:number;value:number}>}
export type WeeklyState={notes:ProcurementNote[];actions:ProcurementAction[];discussions:DiscussionFlag[];overrides:ProcurementOverride[];snapshots:MeetingSnapshot[]}
export type ProcurementRow={project:Project;phase:ProcurementPhase;health:ProcurementHealth;healthReason:string;phaseEnteredAt:string;daysInPhase:number;value:number;lead:string;leadId:string;pm:string;nextAction:string;nextOwner:string;dueDate:string;openActions:number;latestNote?:ProcurementNote;discussion?:DiscussionFlag;vendorException:boolean;stalled:boolean;changes:string[];progress:number;searchText:string}

const KEY='atlas.weeklyProcurement', TYPE='weekly_procurement', EVENT='atlas:weekly-procurement-changed'
const empty=():WeeklyState=>({notes:[],actions:[],discussions:[],overrides:[],snapshots:[]})
export function loadWeeklyState():WeeklyState { const rows=readLocalCollection<WeeklyState>(KEY); return normalize(rows[0]) }
export async function hydrateWeeklyState(){await hydrateLocalCollection<WeeklyState>(KEY,TYPE,'all',{eventName:EVENT});return loadWeeklyState()}
export function saveWeeklyState(state:WeeklyState){saveLocalAndRemoteCollection(KEY,TYPE,'all',[normalize(state)],EVENT)}
function normalize(s?:Partial<WeeklyState>):WeeklyState{return{notes:s?.notes??[],actions:s?.actions??[],discussions:s?.discussions??[],overrides:s?.overrides??[],snapshots:s?.snapshots??[]}}
export function isOverdue(a:ProcurementAction, now=new Date()){return !['Complete','Cancelled'].includes(a.status)&&Boolean(a.dueDate)&&new Date(`${a.dueDate}T23:59:59`).getTime()<now.getTime()}
export function daysBetween(value:string,now=new Date()){if(!value)return 0;return Math.max(0,Math.floor((start(now)-start(new Date(value)))/86400000))}
function start(d:Date){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}

export function determinePhase(p:Project):ProcurementPhase{
  if(['Delivered','Complete','Completed','Cancelled'].includes(String(p.status))||String(p.kitStatus)==='Complete')return'Complete'
  const pos=p.purchaseOrders||[], lines=pos.flatMap(x=>x.lines||[]), ordered=lines.reduce((n,x)=>n+(x.quantityOrdered||0),0),received=lines.reduce((n,x)=>n+(x.quantityReceived||0),0)
  if(['Kitted','Staged','Ready'].includes(p.kitStatus))return'Kitting / Staging'
  if(received>0)return received>=ordered&&ordered>0?'Receiving':'Receiving'
  if(pos.some(po=>po.trackingNumber||po.lines?.some(l=>l.trackingNumber)||['Shipped','In Transit to Cronos'].includes(po.status)))return'Shipping'
  if(pos.length)return'Ordered'
  if(p.status==='Customer Approved'||p.quotes?.some(q=>q.status==='Customer Approved'))return'PO Preparation'
  if(p.quotes?.some(q=>['Quoted','Submitted','Pending Approval'].includes(q.status)))return'Customer Approval / Funding'
  if(p.quotes?.some(q=>q.lines?.length&&q.lines.every(l=>l.unitCost>0)))return'Quote Preparation'
  if((p.quotes?.length||0)>0||(p.quoteLines?.length||0)>0)return'Pricing / RFQ'
  return'New Requirement'
}
export function automaticPhaseEnteredAt(p:Project,phase:ProcurementPhase){const dates:string[]=[];if(phase==='New Requirement')dates.push(p.createdAt||p.startDate);if(['Pricing / RFQ','Quote Preparation','Customer Approval / Funding'].includes(phase))dates.push(...p.quotes.map(q=>q.createdAt));if(['Ordered','Shipping','Receiving'].includes(phase))dates.push(...p.purchaseOrders.map(po=>po.dateIssued));if(phase==='Shipping')dates.push(...p.purchaseOrders.flatMap(po=>po.lines.map(l=>l.estimatedShipDate||'')));if(phase==='Receiving')dates.push(...p.purchaseOrders.flatMap(po=>po.lines.map(l=>l.receivedDate||'')));return dates.filter(Boolean).sort().at(-1)||p.updatedAt||p.createdAt||new Date().toISOString()}
export function buildRows(projects:Project[],users:UserProfile[],state:WeeklyState,now=new Date()):ProcurementRow[]{
 const last=state.snapshots.slice().sort((a,b)=>b.meetingDate.localeCompare(a.meetingDate))[0]
 return projects.filter(p=>!['Cancelled'].includes(p.status)).map(p=>{const o=state.overrides.find(x=>x.projectId===p.id),phase=o?.phase||determinePhase(p),phaseEnteredAt=o?.phaseEnteredAt||automaticPhaseEnteredAt(p,phase),daysInPhase=daysBetween(phaseEnteredAt,now),actions=state.actions.filter(a=>a.projectId===p.id&&!['Complete','Cancelled'].includes(a.status)),overdue=actions.filter(a=>isOverdue(a,now)),discussion=state.discussions.find(d=>d.projectId===p.id&&!d.resolvedAt),pos=p.purchaseOrders||[],allLines=pos.flatMap(po=>po.lines||[]),ordered=allLines.reduce((n,l)=>n+(l.quantityOrdered||0),0),received=allLines.reduce((n,l)=>n+(l.quantityReceived||0),0),vendorException=allLines.some(l=>/backorder|discrep/i.test(`${l.status} ${l.notes||''}`))||pos.some(po=>Boolean(po.estimatedShipDate)&&!po.trackingNumber&&new Date(po.estimatedShipDate!).getTime()<now.getTime()),dueDate=[p.endDate,...actions.map(a=>a.dueDate)].filter(Boolean).sort()[0]||'',stalled=phase!=='Complete'&&daysInPhase>(phase==='Pricing / RFQ'||phase==='Customer Approval / Funding'?14:30),systemHealth:ProcurementHealth=phase==='Complete'?'Complete':overdue.length>0&&daysBetween(overdue[0].dueDate,now)>7?'Critical':vendorException||overdue.length>0||stalled||discussion?'Attention':'On Track',health=o?.health||systemHealth,value=pos.reduce((n,po)=>n+(po.totalCost||0),0)||p.materialBudget||p.checkbookStartingBalance||0,owner=users.find(u=>p.assignedUserIds?.includes(u.id)),latestNote=state.notes.filter(n=>n.projectId===p.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],previous=last?.projects[p.id],trackingCount=new Set(pos.flatMap(po=>[po.trackingNumber,...po.lines.map(l=>l.trackingNumber)].filter(Boolean))).size,changes:string[]=[];
 if(previous){if(pos.length>previous.poCount)changes.push(`+${pos.length-previous.poCount} POs issued`);if(value>previous.poValue)changes.push(`${money(value-previous.poValue)} newly committed`);if(trackingCount>previous.trackingCount)changes.push(`+${trackingCount-previous.trackingCount} tracking numbers`);if(received>previous.received)changes.push(`${received-previous.received} items received`);if(phase!==previous.phase)changes.push(`${previous.phase} → ${phase}`);if(health!==previous.health)changes.push(`Status changed to ${health}`)}
 const next=actions.sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];const nextAction=next?.description||(phase==='New Requirement'?'Confirm scope and pricing requirements':phase==='Pricing / RFQ'?'Obtain vendor pricing':phase==='Customer Approval / Funding'?'Secure customer approval / funding':phase==='PO Preparation'?'Issue remaining purchase orders':phase==='Shipping'?'Confirm vendor ETA and tracking':phase==='Receiving'?'Reconcile receipts':'Review next procurement milestone')
 return{project:p,phase,health,healthReason:o?.reason||(vendorException?'Vendor/shipping exception':overdue.length?'Overdue action':stalled?`${daysInPhase} days in phase`:discussion?.reason||'No active exception'),phaseEnteredAt,daysInPhase,value,lead:owner?.name||'Unassigned',leadId:owner?.id||'',pm:p.projectManager||'Unassigned',nextAction,nextOwner:next?.ownerName||owner?.name||'Unassigned',dueDate,openActions:actions.length,latestNote,discussion,vendorException,stalled,changes,progress:Math.round(PROCUREMENT_PHASES.indexOf(phase)/(PROCUREMENT_PHASES.length-1)*100),searchText:[p.projectName,p.projectNumber,p.customer,p.projectManager,owner?.name,...p.quotes.flatMap(q=>q.lines.flatMap(l=>[l.manufacturer,l.vendor,l.partNumber])),...pos.flatMap(po=>[po.poNumber,po.vendor,...po.lines.flatMap(l=>[l.manufacturer,l.partNumber])]),...state.notes.filter(n=>n.projectId===p.id).map(n=>n.text)].join(' ').toLowerCase()}
 }).filter(r=>r.phase!=='Complete'||daysBetween(r.phaseEnteredAt,now)<=30)
}
export function makeSnapshot(rows:ProcurementRow[],session:UserSession):MeetingSnapshot{return{id:crypto.randomUUID(),meetingDate:new Date().toISOString().slice(0,10),createdBy:session.id,createdAt:new Date().toISOString(),projects:Object.fromEntries(rows.map(r=>[r.project.id,{phase:r.phase,health:r.health,poCount:r.project.purchaseOrders.length,poValue:r.project.purchaseOrders.reduce((n,p)=>n+p.totalCost,0),trackingCount:new Set(r.project.purchaseOrders.flatMap(p=>[p.trackingNumber,...p.lines.map(l=>l.trackingNumber)].filter(Boolean))).size,received:r.project.purchaseOrders.flatMap(p=>p.lines).reduce((n,l)=>n+l.quantityReceived,0),value:r.value}]))}}
export function agingBucket(days:number){return days<=7?'0–7':days<=14?'8–14':days<=30?'15–30':'30+'}
function money(v:number){return new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v)}
