<template>
  <div class="product-detail-page">
    <header class="page-heading"><div><RouterLink class="text-link" to="/catalog">← Product Catalog</RouterLink><h1>{{ product?.manufacturer }} {{ product?.manufacturer_part_number }}</h1><p>{{ product?.description }}</p></div><button v-if="isAdmin && product" class="secondary-action" type="button" @click="editing = !editing"><Pencil :size="17" />{{ editing ? 'Cancel Edit' : 'Edit Product' }}</button></header>
    <p v-if="error" class="status-note">{{ error }}</p>
    <template v-if="product">
      <section v-if="editing" class="detail-card edit-card"><h2>Edit Catalog Record</h2><div class="edit-grid"><label>Manufacturer<input v-model="form.manufacturer" /></label><label>Part Number<input v-model="form.manufacturerPartNumber" /></label><label>Current Cost<input v-model.number="form.currentCost" type="number" min="0" step="0.01" /></label><label>Supplier<input v-model="form.supplier" /></label><label>Supplier Part Number<input v-model="form.supplierPartNumber" /></label><label>Lead Time<input v-model="form.leadTime" /></label><label>Category<input v-model="form.category" /></label><label>Description<textarea v-model="form.description" /></label></div><button class="primary-action" type="button" @click="save">Save Product</button></section>
      <section class="product-summary-grid"><div><span>Current Cost</span><strong>{{ currency(product.current_cost ?? 0) }}</strong></div><div><span>Average Purchased Cost</span><strong>{{ currency(averageCost) }}</strong></div><div><span>Last Purchased</span><strong>{{ lastPurchased }}</strong></div><div><span>Supplier</span><strong>{{ product.supplier || 'Not assigned' }}</strong></div><div><span>Lead Time</span><strong>{{ product.lead_time || 'Unknown' }}</strong></div><div><span>Status</span><strong>{{ product.procurement_status || (product.active ? 'Active' : 'Inactive') }}</strong></div></section>
      <div class="detail-grid-layout">
        <section class="detail-card"><h2>Product Information</h2><dl><template v-for="item in fields" :key="item.label"><dt>{{ item.label }}</dt><dd>{{ item.value }}</dd></template></dl></section>
        <section class="detail-card"><h2>Specifications</h2><p v-if="!Object.keys(product.specifications || {}).length">No structured specifications yet. Image and distributor specification feeds are reserved for a future integration.</p><dl v-else><template v-for="(value,key) in product.specifications" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></template></dl></section>
      </div>
      <section class="detail-card"><h2>Pricing History</h2><table><thead><tr><th>Effective Date</th><th>Previous Cost</th><th>New Cost</th><th>Difference</th><th>Change</th><th>Source</th></tr></thead><tbody><tr v-for="row in pricingHistory" :key="String(row.id)"><td>{{ formatDate(String(row.effective_date)) }}</td><td>{{ row.previous_cost == null ? 'Initial' : currency(Number(row.previous_cost)) }}</td><td>{{ currency(Number(row.new_cost)) }}</td><td>{{ currency(Number(row.change_amount || 0)) }}</td><td>{{ row.change_percent == null ? '—' : `${Number(row.change_percent).toFixed(1)}%` }}</td><td>{{ row.source_file }}</td></tr></tbody></table></section>
      <section class="detail-card"><h2>Procurement &amp; Project History</h2><div v-if="usage.length" class="usage-list"><RouterLink v-for="item in usage" :key="item.key" :to="`/projects/${item.projectId}`"><strong>{{ item.projectNumber }}</strong><span>{{ item.projectName }} · {{ item.poNumber }} · {{ item.quantity }} units at {{ currency(item.cost) }}</span></RouterLink></div><p v-else>No Atlas purchase orders currently reference this manufacturer and part number.</p></section>
      <section class="detail-card"><h2>Related Products</h2><div class="related-grid"><RouterLink v-for="item in relatedProducts" :key="item.id" :to="`/catalog/${item.id}`"><strong>{{ item.manufacturer }} {{ item.manufacturer_part_number }}</strong><span>{{ item.description }}</span><small>{{ currency(item.current_cost ?? 0) }}</small></RouterLink></div></section>
    </template>
  </div>
</template>
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'; import { useRoute } from 'vue-router'; import { Pencil } from '@lucide/vue'; import { currency } from '../services/calculations'; import { formatDisplayDate } from '../services/dateFormat'; import { fetchSession } from '../services/auth'; import { loadProjects } from '../services/localProjects'; import { loadCatalogProduct, updateCatalogProduct, type CatalogProduct } from '../services/productCatalogApi'
const route=useRoute(); const product=ref<CatalogProduct>(); const pricingHistory=ref<Array<Record<string,unknown>>>([]); const relatedProducts=ref<CatalogProduct[]>([]); const error=ref(''); const editing=ref(false); const form=reactive({manufacturer:'',manufacturerPartNumber:'',description:'',currentCost:0,supplier:'',supplierPartNumber:'',leadTime:'',category:''}); const isAdmin=computed(()=>fetchSession()?.role==='Admin')
const fields=computed(()=>product.value?[{label:'Manufacturer',value:product.value.manufacturer},{label:'Manufacturer Part Number',value:product.value.manufacturer_part_number},{label:'Description',value:product.value.description},{label:'Category',value:product.value.category||'—'},{label:'Subcategory',value:product.value.subcategory||'—'},{label:'Budget Unit Price',value:currency(product.value.budget_unit_price??0)},{label:'Unit of Measure',value:product.value.unit_of_measure||'—'},{label:'Supplier Part Number',value:product.value.supplier_part_number||'—'},{label:'FSC',value:product.value.fsc||'—'},{label:'NSN',value:product.value.nsn||'—'},{label:'DPAS',value:product.value.dpas||'—'},{label:'Purchasable',value:yesNo(product.value.purchasable)},{label:'TAA Compliant',value:yesNo(product.value.taa_compliant)},{label:'In Stock',value:yesNo(product.value.in_stock)},{label:'Serial Number Required',value:yesNo(product.value.serial_number_required)},{label:'Last Updated',value:formatDate(product.value.updated_at)},{label:'Source File',value:product.value.source_file||'—'}]:[])
const usage=computed(()=>{if(!product.value)return[];const key=(value:string)=>value.trim().toLowerCase();return loadProjects().flatMap(project=>project.purchaseOrders.flatMap(po=>po.lines.filter(line=>key(line.partNumber)===key(product.value!.manufacturer_part_number)&&(!line.manufacturer||key(line.manufacturer)===key(product.value!.manufacturer))).map(line=>({key:`${project.id}:${po.id}:${line.id}`,projectId:project.id,projectNumber:project.projectNumber,projectName:project.projectName,poNumber:po.poNumber,date:po.dateIssued,quantity:line.quantityOrdered,cost:line.unitCost}))))})
const averageCost=computed(()=>usage.value.length?usage.value.reduce((sum,item)=>sum+item.cost,0)/usage.value.length:(product.value?.current_cost??0)); const lastPurchased=computed(()=>usage.value.length?formatDate([...usage.value].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime())[0].date):'No purchases')
watch(()=>route.params.productId,load,{immediate:true}); async function load(){try{const result=await loadCatalogProduct(String(route.params.productId));product.value=result.product;pricingHistory.value=result.pricingHistory;relatedProducts.value=result.relatedProducts;Object.assign(form,{manufacturer:result.product.manufacturer,manufacturerPartNumber:result.product.manufacturer_part_number,description:result.product.description,currentCost:result.product.current_cost??0,supplier:result.product.supplier,supplierPartNumber:result.product.supplier_part_number,leadTime:result.product.lead_time,category:result.product.category})}catch(cause){error.value=cause instanceof Error?cause.message:'Unable to load product.'}}
async function save(){if(!product.value)return;try{const result=await updateCatalogProduct(product.value.id,{...form});product.value=result.product;editing.value=false;await load()}catch(cause){error.value=cause instanceof Error?cause.message:'Unable to save product.'}}
function yesNo(value:boolean|null){return value===null?'Unknown':value?'Yes':'No'} function formatDate(value:string){return formatDisplayDate(value)}
</script>
<style scoped>.product-detail-page{display:grid;gap:1rem}.page-heading h1{margin:.4rem 0}.product-summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem}.product-summary-grid div,.detail-card{background:#fff;border:1px solid #dbe3ec;border-radius:14px;padding:1rem}.product-summary-grid span,.product-summary-grid strong{display:block}.product-summary-grid span{font-size:.75rem;color:#64748b}.product-summary-grid strong{font-size:1.05rem;margin-top:.25rem}.detail-grid-layout{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.detail-card h2{margin-top:0}.detail-card dl{display:grid;grid-template-columns:180px 1fr;gap:.55rem;margin:0}.detail-card dt{font-size:.78rem;color:#64748b}.detail-card dd{margin:0}.detail-card table{width:100%;border-collapse:collapse}.detail-card th,.detail-card td{text-align:left;border-bottom:1px solid #e2e8f0;padding:.65rem;font-size:.82rem}.related-grid,.usage-list{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem}.related-grid a,.usage-list a{display:grid;gap:.25rem;border:1px solid #e2e8f0;border-radius:10px;padding:.8rem;color:inherit;text-decoration:none}.related-grid span,.usage-list span{color:#64748b;font-size:.8rem}.edit-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem;margin-bottom:1rem}.edit-grid label{display:grid;gap:.35rem;font-size:.78rem;font-weight:700;color:#475569}.edit-grid input,.edit-grid textarea{border:1px solid #cbd5e1;border-radius:8px;padding:.55rem}.edit-grid textarea{min-height:70px}@media(max-width:900px){.product-summary-grid,.detail-grid-layout,.related-grid,.usage-list,.edit-grid{grid-template-columns:1fr}}</style>
